#cloud-config

coreos:
    
  units:
    - name: etcd-member.service
      enable: true
      command: start
      drop-ins:
        - name: 40-etcd-cluster.conf
          content: |
            [Service]
            Environment="ETCD_IMAGE_TAG=v2.1.3"
            Environment="ETCD_NAME=digitalocean1"
            Environment="ETCD_ADVERTISE_CLIENT_URLS=http://10.62.42.3:2379"
            Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.62.42.3:2380"
            Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
            Environment="ETCD_LISTEN_PEER_URLS=http://10.62.42.3:2380"
            Environment="ETCD_DISCOVERY=https://discovery.etcd.io/d0cbca8cf4000cf680915b8fdd601ec3"
            

    # enable and start iptables-restore
    - name: iptables-restore.service
      enable: true
      command: start

    # Our elastic network
    #change the servername to fit our server naming convetion, and AWS information
    - name: docker-bizElasticNetwork.service
      command: start
      content: |
        [Unit]
        Description=Labizbille distributed elastic service
        After=docker.service

        [Service]
        Restart=always
        ExecStartPre=-/usr/bin/docker rm bizElasticNetwork
        ExecStart=/usr/bin/docker run --rm --net=host     --device=/dev/net/tun     --cap-add NET_ADMIN     --volume /srv/tinc:/etc/tinc   --name bizElasticNetwork labizbille/elasticnetwork
        ExecStop=/usr/bin/docker stop -t 2 bizElasticNetwork

write_files:
    # 8051:elastic network status, tun0 to eth0 so that docker containers can acces etcd2
  - path: /var/lib/iptables/rules-save
    permissions: 0644
    content: |
      *filter
      :INPUT DROP [0:0]
      :FORWARD DROP [0:0]
      :OUTPUT ACCEPT [0:0]
      -A INPUT -i lo -j ACCEPT
      -A INPUT -i tun0 -j ACCEPT
      -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
      -A INPUT -i eth0 -p tcp -m tcp --dport 80 -j ACCEPT
      -A INPUT -i eth0 -p tcp -m tcp --dport 8051 -j ACCEPT
      -A INPUT -i eth0 -p tcp -m tcp --dport 655 -j ACCEPT
      -A INPUT -i eth0 -p udp -m udp --dport 655 -j ACCEPT
      -A INPUT -d $public_ipv4/32 -p icmp -m icmp --icmp-type 8 -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT
      -A FORWARD -i tun0 -o eth0 -j ACCEPT
      COMMIT

  # bizElasticNetwork appsettings
  - path: /srv/tinc/appsettings.json
    permissions: 0644
    owner: root
    content: |
      {
      "serverPublicIp":"$public_ipv4",
      "serverName": "digitalocean1",
      "serverPrivateIp": "10.62.42.3",
      "s3BucketName": "myelasticnetworkdata",
      "s3AccessKey": "B+u5MHqKOMxyUoonfBhBLq1T69FciqWyGHJ9hiC+",
      "s3AccessId": "AKIAIWIYQODNHJELAYMQ"
      }

  # registry files
  - path: /etc/docker/certs.d/myswarmregistry.labizbille.com:5000/ca.crt
    permissions: 0644
    owner: root
    content: |
        -----BEGIN CERTIFICATE-----
        MIIFrzCCA5egAwIBAgIJAP7/KYY4ilY/MA0GCSqGSIb3DQEBCwUAMG4xCzAJBgNV
        BAYTAlVTMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
        aWRnaXRzIFB0eSBMdGQxJzAlBgNVBAMMHm15c3dhcm1yZWdpc3RyeS5sYWJpemJp
        bGxlLmNvbTAeFw0xODAzMTQwNTA0MzlaFw0xOTAzMTQwNTA0MzlaMG4xCzAJBgNV
        BAYTAlVTMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
        aWRnaXRzIFB0eSBMdGQxJzAlBgNVBAMMHm15c3dhcm1yZWdpc3RyeS5sYWJpemJp
        bGxlLmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAL3Au5lefVpJ
        HP97eyF4lIKvbo4URe49/bOOJEw8rVgu8x3tLQErQ62U6JfHwYfOOW55F7UhN3h0
        UgybWep/U31Kugc2vuICyLVJffYQYpqqx7pEO7cMeVjNtmB9E9qx4QaKxcZLOhkI
        /F0pxfORnfghXiN9NNzi9M6dBIrPnu2G4/R0GsdY2KJrGis+yNrHs97SqIp8vQVc
        CyFapJZCVvdPUNxgAjv4O6+FEJwn42MOTGcoHyhkwIiS48+a6Bq1eAELB24JLnHU
        m6sYma+GyrkXwMeV2050UFoJV3Lap5rQmbOCPcz/uIEfQTrMbwhPcVmQDMH/AnbT
        CLIfoAR0oY3/HhY8RuARa5PMGKDFrAyKZf0Uo6BKdmRkpsWKk0wmF3p0xNonQ4de
        jWt4vKehAaDGEoGxAQqV7fwJpx4SdCKiWFwz6vw2l3T02W3W1SVmko3qQqo6dTsq
        Qmw/8HxXIQ5U7KXBsK1fUTmG87RBH3mCnN54nhuhoo/mqAjh6MIC3U8RacnJYYpn
        ZaDw1zdjPkAb/+lpXQinyqk+5K5uaJGxCBFBG4GzJMa7YModmgWXekBSVCxAfJ5v
        lQwGhvS0NsX0o6y0hPKadQ9XHJs0ru8lLzwRlyK4eE8PsTaJAmJ9gAXwMdA4L013
        xYo+Vb7QRNBlpGkKvC0bln04ixfZHnOnAgMBAAGjUDBOMB0GA1UdDgQWBBSiLgAS
        ZRyItqzmUqQp5/1ncbccbDAfBgNVHSMEGDAWgBSiLgASZRyItqzmUqQp5/1ncbcc
        bDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQBWo1CeGGjsEFbdygNC
        leWlreCvoKXLuHnaGTwpcuk8QnUq/iPjtO25uQQ+853UQSJjZaC0IBZlv8ZK7ND+
        drx2FZEyfZIDGsXMyG5LIOfsrMjqgaRs6rV6JxzZytUCnrlr2AOEqbmsnD/g7bP4
        gQBtl3yPYrjMnaS0ty+yU83CLa8FZzxALc4KPuY0FIjjIF9b4zdBSwP/DNhN/doN
        yJo8aW530b4u4PTTOnEWkiioFy7PIcRELa9SjOyeCfcogsyAS2mR6cE/bSemrJV9
        caH4WdWbKUmfHsOWNYxKPXwh3aecr7V91VLNPmjzYndxModqQaBej2D0ATc9BLir
        ynu25odeNrIk6b1BBXKZgBluf/eisDLUNLngLOstP6vReLNfFV/dmE7cRtdiaCKo
        98xMxk5LReK5i0qWsnFp93t3eeur3sCrPUSwrYiJNT8DgqCg9Ljy88iyBBY3EUff
        uvsTFOUneW9sRG/3Prvm1yCxchjfuFG265NlXH99WQ5L/UQBD3mkojGFDrgKqg1v
        ae968nSZR+co+Z22d3GRHOE9cFZpSyQsYn6r97zdF4+r/DRmZPq8koZ4PxOAov2E
        IlETxYlZ8bKOlD62gzVHmkdhpb6i29pIsMTY2ksdJ4UChoMf/o5foM0Ov/KvMV1e
        xYsgGmbkrDgJ/rA0pEMQdfATvA==
        -----END CERTIFICATE-----







  